import {
  actorSchema,
  approvalDecisionRequestSchema,
  approvalDecisionResponseSchema,
  approvalRequestSchema,
  browserNavigatedSchema,
  browserSensitiveActionRequestSchema,
  browserStartedSchema,
  browserTwoFactorRequestSchema,
  browserUserTakeoverChangedSchema,
  browserUserTakeoverRequestSchema,
  createSessionRequestSchema,
  createSessionResponseSchema,
  getSessionResponseSchema,
  listSessionsResponseSchema,
  remoteErrorSchema,
  remoteEventEnvelopeSchema,
  secretGrantResponseSchema,
  secretRequestSchema,
  sendInstructionRequestSchema,
  sendInstructionResponseSchema,
  sessionDescriptorSchema,
  stopSessionRequestSchema,
  stopSessionResponseSchema,
  terminalExitedSchema,
  terminalInputSchema,
  terminalOpenedSchema,
  terminalOutputSchema,
  terminalResizeSchema,
  uatRouteCreatedSchema,
  uatRouteExpiredSchema,
} from "./schemas/index.js";

export const remoteOpenApiComponents = {
  schemas: {
    Actor: actorSchema,
    ApprovalDecisionRequest: approvalDecisionRequestSchema,
    ApprovalDecisionResponse: approvalDecisionResponseSchema,
    ApprovalRequest: approvalRequestSchema,
    BrowserNavigated: browserNavigatedSchema,
    BrowserSensitiveActionRequest: browserSensitiveActionRequestSchema,
    BrowserStarted: browserStartedSchema,
    BrowserTwoFactorRequest: browserTwoFactorRequestSchema,
    BrowserUserTakeoverChanged: browserUserTakeoverChangedSchema,
    BrowserUserTakeoverRequest: browserUserTakeoverRequestSchema,
    CreateSessionRequest: createSessionRequestSchema,
    CreateSessionResponse: createSessionResponseSchema,
    GetSessionResponse: getSessionResponseSchema,
    ListSessionsResponse: listSessionsResponseSchema,
    RemoteError: remoteErrorSchema,
    RemoteEventEnvelope: remoteEventEnvelopeSchema,
    SecretGrantResponse: secretGrantResponseSchema,
    SecretRequest: secretRequestSchema,
    SendInstructionRequest: sendInstructionRequestSchema,
    SendInstructionResponse: sendInstructionResponseSchema,
    SessionDescriptor: sessionDescriptorSchema,
    StopSessionRequest: stopSessionRequestSchema,
    StopSessionResponse: stopSessionResponseSchema,
    TerminalExited: terminalExitedSchema,
    TerminalInput: terminalInputSchema,
    TerminalOpened: terminalOpenedSchema,
    TerminalOutput: terminalOutputSchema,
    TerminalResize: terminalResizeSchema,
    UatRouteCreated: uatRouteCreatedSchema,
    UatRouteExpired: uatRouteExpiredSchema,
  },
} as const;
